name: Compila y Genera PDF

on:
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
      - name: Tener copia local del repo
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET en el runner
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

  crear-pdf:
    runs-on: ubuntu-latest
    needs: compila  # Este job se ejecuta después del job "compila"

    steps:
      - name: Tener copia local del repo
        uses: actions/checkout@v3

      - name: Convertir Markdown a PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: true

      - name: Subir PDFs generados
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
        
